/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_siriusyang_retrofitdemo_navtivemeath_JniUtils */

#ifndef _Included_com_siriusyang_retrofitdemo_navtivemeath_JniUtils
#define _Included_com_siriusyang_retrofitdemo_navtivemeath_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_siriusyang_retrofitdemo_navtivemeath_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_siriusyang_retrofitdemo_navtivemeath_JniUtils_getStringFormC
        (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
